repos:
  # Ruff: linter + import sorting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff-check
        args: [--fix]   # auto-fix issues (respects pyproject.toml)

  # Black: code formatting
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
