name: Build and Release Executable

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag to use for the release'
        required: true
        type: string

jobs:
  build-exe:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Make executable
        run: pyinstaller bloatware-remover.spec
      - name: Rename executable
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            mv dist/bloatware-remover dist/bloatware-remover-windows.exe
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            mv dist/bloatware-remover dist/bloatware-remover-linux
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            mv dist/bloatware-remover dist/bloatware-remover_macos
          fi
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bloatware-remover-${{ matrix.os }}
          path: dist/*

  release:
    needs: build-exe
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: List downloaded files (Debugging)
        run: ls -R

      - name: Make files executable (Linux/Mac)
        run: chmod +x app-* || true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: Release ${{ github.event.inputs.tag }}
          draft: false
          prerelease: false
          files: |
            bloatware-remover-linux
            bloatware-remover-windows.exe
            bloatware-remover-macos
