name: Build Executable

on:
  workflow_dispatch:

jobs:
  build-exe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Make build_exe.sh executable
        run: chmod +x build_exe.sh
      - name: Build executable with PyInstaller
        run: ./build_exe.sh

